### ISSUE TITLE
Darkmode please

### ISSUE THREAD

**Issue by tomByrer** [vikejs/libframe#2]
Actually semi A11y for me; my concussion makes all-white sites give me minor eye/head strains.

**Comment by brillout** [comment]
Let's solve this A11y problem once and for all: we should (if it doesn't exist) implement a little JavaScript library (I expect it to be only a couple lines of codes) that inverts the colors of the page? That should do the trick, right?

**Comment by brillout** [comment]
This lib could then be integrated into any website.

**Comment by brillout** [comment]
Closing, PR welcome.
