### ISSUE TITLE
Bug: jumping to sub-topics doesn't

### ISSUE THREAD

**Issue by tomByrer** [vikejs/libframe#3]
EG: https://telefunc.com/tour#telefunctions-need-protection
Only goes to the Tour page, but does **not** jump to 
`<h2>Telefunctions need protection</h2>`

Brave/Chromium
Firefox

edit: just remembered; easy fix: headers need ids, eg
`<h2 id="telefunctions-need-protection">Telefunctions need protection</h2>`
  Maybe I could do it; let me see if I have time

TIA :)

**Comment by brillout** [comment]
Thanks will fix it :)

Note that Telefunc is work-in-progress though; so expect many bugs like this atm.
